EcoTrend Industry Project/Controllers/HomeController.cs
using EcoTrend_Industry_Project.BusinessLogic;
using EcoTrend_Industry_Project.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.Owin.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using EcoTrend_Industry_Project.Repositories;
using PagedList;

namespace EcoTrend_Industry_Project.Controllers
{
    public class HomeController : BaseController
    {
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(Login login)
        {
            UserStore<IdentityUser> userStore = new UserStore<IdentityUser>();
            UserManager<IdentityUser> manager = new UserManager<IdentityUser>(userStore);
            try
            {
                IdentityUser identityUser = manager.Find(login.UserName,
                                                             login.Password);
                if (ModelState.IsValid)
                {
                    if (identityUser != null)
                    {
                        IAuthenticationManager authenticationManager = HttpContext.GetOwinContext().Authentication;
                        authenticationManager.SignOut(DefaultAuthenticationTypes.ExternalCookie);

                        var identity = new ClaimsIdentity(new[] {
                                            new Claim(ClaimTypes.Name, login.UserName),
                                            },
                                            DefaultAuthenticationTypes.ApplicationCookie,
                                            ClaimTypes.Name, ClaimTypes.Role);
                        // SignIn() accepts ClaimsIdentity and issues logged in cookie. 

                        var userSearched = manager.FindByName(login.UserName);

                        if (manager.IsLockedOut(userSearched.Id))
                        {
                            return View();
                        }
                        else
                        {

                            authenticationManager.SignIn(new AuthenticationProperties
                            {
                                IsPersistent = false
                            }, identity);

                            EcotrendEntities context = new EcotrendEntities();
                            var user = context.AspNetUsers.Where(u => u.UserName == login.UserName).FirstOrDefault();
                            var role = manager.GetRoles(user.Id);

                            if (role[0] == "salesrep")
                            {
                                return RedirectToAction("ContactManagement", "Home");
                            }
                            else if (role[0] == "admin")
                            {
                                return RedirectToAction("ListSalesReps", "Admin");
                            }
                            else if (role[0] == "supplier")
                            {
                                return RedirectToAction("Index", "Supplier");
                            }

                        }

                    }
                }
                return View();
            }
            catch
            {
                return View();
            }
        }

        [Authorize(Roles = "admin, salesrep")]
        public ActionResult ContactManagement(string sortOrder, string currentFilter, string searchString, int? page)
        {
            int salesRepID = 0;
            if (User.Identity.Name != "admin")
            {
                salesRepID = int.Parse(User.Identity.Name);
            }
            ContactRepo contactRepo = new ContactRepo();
            if (searchString != null)
                page = 1;
            else
                searchString = currentFilter;

            IEnumerable<ContactVM> contacts = contactRepo.GetContactsBySalesRepID(searchString, sortOrder, salesRepID);

            // Store current search and sort filter parameters.
            ViewBag.CurrentFilter = searchString;
            ViewBag.CurrentSort = sortOrder;

            // Provide toggle option for name sort.
            if (String.IsNullOrEmpty(sortOrder))
                ViewBag.NameSortParm = ContactRepo.LASTNAME;
            else
                ViewBag.NameSortParm = "";

            //// Provide toggle  optionfor date sort.
            //if (sortOrder == StudentRepository.DATE)
            //    ViewBag.DateSortParm = StudentRepository.DATE_DESC;
            //else
            //    ViewBag.DateSortParm = StudentRepository.DATE;
            const int PAGE_SIZE = 3;
            int pageNumber = (page ?? 1);

            // Truncate results to fit in the view provided.
            contacts = contacts.ToPagedList(pageNumber, PAGE_SIZE);

            return View(contacts);


        }

        [HttpGet]
        public ActionResult SendEmail()
        {

            // EmailMessageVM e                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            M = new EmailMessageVM();
            //   return View(emailMessageVM);
            return View();
        }

        [HttpPost]
        public ActionResult SendEmail(string sender, string subject, string body)
        {
            ContactRepo contactRepo = new ContactRepo();
            /* List<SampleContact> contactList = contactRepo.GetAll().ToList();

             string ErrorMessage = "";
             foreach (var item in contactList)
             {
                 MailHelper mailer = new MailHelper();
                 string response = mailer.EmailFromArvixe(
                                            new Message(sender, subject, body, item.email));
                 if (!response.Contains("success"))
                 {
                     ErrorMessage = ErrorMessage + item.email + " Failed \n";
                     return RedirectToAction("emailMessageList", "Home", new { ErrorMessage = ErrorMessage });
                 }
             }*/
            return View();
        }

        public ActionResult emailMessageList(string ErrorMessage)
        {
            ViewBag.ErrorMessage = ErrorMessage;
            return View();
        }


        public ActionResult Result(bool success, string result)
        {
            if (success == true)
            {
                ViewBag.TabTitle = "Success";
                ViewBag.Result = result;
            }
            else
            {
                ViewBag.TabTitle = "Error";
                ViewBag.Result = result;
            }
            return View();
        }

        public ActionResult Delete(int id)
        {

            ContactRepo contactRepo = new ContactRepo();
            if (contactRepo.Delete(id) == true)
            {
                return RedirectToAction("ContactManagement");
            }
            return View();
        }
        [HttpGet]
        public ActionResult Test()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Test(string str)
        {
            try
            {
                EmailRepo emailRepo = new EmailRepo();
                List<string> emails = new List<string>();
                emails.Add("andrew.hui09@gmail.com");
                emails.Add("hui_andrew@hotmail.com");
                emailRepo.MassSend(emails, "sender", "somesubjcct", "abcBody");

                ViewBag.Success = "Emails sent.";
                return RedirectToAction("Result", "Home", new { success = true, result = ViewBag.Success });
            }
            catch
            {
                ViewBag.Error = "Emails were not sent.";
                return RedirectToAction("Result", "Home", new { success = false, result = ViewBag.Error });
            }
        }
        public void emailArray()
        {
            string[] emailaddresses = new string[] { "andrew.hui09@gmail.com", "hui_andrew@hotmail.com" };
            for (int i = 0; i < emailaddresses.Count(); i++)
            {
                MailHelper mailer = new MailHelper();
                string response = mailer.EmailFromArvixe(new Message("andrew.hui09@gmail.com", "someSubject", "someBody", emailaddresses[i]));
            }
        }



    }
}

EcoTrend Industry Project/Controllers/SalesRepController.cs
using EcoTrend_Industry_Project.Models;
using EcoTrend_Industry_Project.Repositories;
using EcoTrend_Industry_Project.ViewModels;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EcoTrend_Industry_Project.Controllers
{
    [Authorize(Roles = "admin, salesrep")]
    public class SalesRepController : BaseController
    {
        // GET: Contact
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult AddContact()
        {
            StoreRepo storeRepo = new StoreRepo();
            return View(storeRepo.GetStoresUnderContactVM());
        }
        [HttpPost]
        public ActionResult AddContact(ContactVM contactVM)
        {
            int salesRepID = Convert.ToInt32(User.Identity.Name);
            contactVM.SalesRepID = salesRepID;
            StoreRepo storeRepo = new StoreRepo();
            contactVM.StoreName = storeRepo.GetStoreNameByID(Convert.ToInt32(contactVM.StoreID));
            ContactRepo contactRepo = new ContactRepo();

            try
            {
                contactRepo.AddContact(contactVM);
                ViewBag.Success = "Contact successfully added.";
                return RedirectToAction("Result", "Home", new { success = true, result = ViewBag.Success });
            }
            catch
            {
                ViewBag.Error = "Failed to add contact.";
                return RedirectToAction("Result", "Home", new { success = false, result = ViewBag.Error });
            }



        }

        [HttpGet]
        public ActionResult EditContact(string id)
        {
            StoreRepo storeRepo = new StoreRepo();
            ContactRepo contactRepo = new ContactRepo();
            ContactVM contactVm = contactRepo.GetContactDetail(Convert.ToInt32(id));
            //queries stores and gets them from the database, and puts them in the edit viewmodel.
            contactVm.Stores = storeRepo.GetStoresUnderContactVM().Stores;
            return View(contactVm);
        }
        [HttpPost]
        public ActionResult EditContact(ContactVM contactVM)
        {
            contactVM.SalesRepID = Convert.ToInt32(User.Identity.Name);
            /*  if (department == "success")
              {
                  ViewBag.Success = "Contact successfully updated.";
                  return RedirectToAction("Result", "Home", new { success = true, result = ViewBag.Success });
              }
              else
              {
                  ViewBag.Error = "Contact was not updated.";
                  return RedirectToAction("Result", "Home", new { success = false, result = ViewBag.Error });
              } */
            ContactRepo contactRepo = new ContactRepo();
            ContactVM editedContact = contactRepo.LimitedUpdate(contactVM);

            return RedirectToAction("ContactManagement", "Home");

        }

        public ActionResult AddSalesRep()
        {
            return View();
        }
        public ActionResult ListSalesReps()
        {
            return View();
        }
        public ActionResult ContactNotes(int id, int contactId, string firstName, string lastName)
        {
            LogsRepo logsRepo = new LogsRepo();
            var logs = logsRepo.GetAllVM(id, contactId);
            ViewBag.FirstName = firstName;
            ViewBag.LastName = lastName;
            ViewBag.ContactId = contactId;
            return View(logsRepo.GetLogsBySalesIDContactID(id, contactId));
        }

        [HttpGet]
        public ActionResult AddNote(int contactId, string firstName, string lastName)
        {
            EcotrendEntities context = new EcotrendEntities();
            ViewBag.ContactId = contactId;
            ViewBag.FirstName = firstName;
            ViewBag.LastName = lastName;
            return View();
        }
        [HttpPost]
        public ActionResult AddNote(string title, string body, int contactID)
        {
            EcotrendEntities context = new EcotrendEntities();
            LogsRepo logsRepo = new LogsRepo();

            int parsedUserName;
            int.TryParse(User.Identity.Name, out parsedUserName);

            var salesRepName = logsRepo.GetSalesRepName(parsedUserName);

            Log log = new Log();
            log = logsRepo.AddLog(title, body, contactID, salesRepName);
            log.salesRepID = parsedUserName;

            try
            {
                context.Logs.Add(log);
                context.SaveChanges();
                ViewBag.Success = "Note added successfully";

                return RedirectToAction("Result", "Home", new { success = true, result = ViewBag.Success });
            }
            catch
            {
                ViewBag.Error = "Note was not added.";
                return RedirectToAction("Result", "Home", new { success = false, result = ViewBag.Error });
            }
        }
        [HttpGet]
        public ActionResult SendGroupEmail()
        {
            ContactRepo contactRepo = new ContactRepo();
            return View(contactRepo.GetAll());
        }
        [HttpPost]
        public ActionResult SendGroupEmail(List<string> emails, string title, string body)
        {
            EmailRepo emailRepo = new EmailRepo();
            ContactRepo contactRepo = new ContactRepo();
            try
            {
                emailRepo.MassSend(emails, "sender", title, body);
                ViewBag.Success = "Emails sent successfully";
                return View(contactRepo.GetAll());
            }
            catch
            {
                ViewBag.Error = "Uh oh... Something went wrong. Try again";
                return View(contactRepo.GetAll());
            }
        }


        public ActionResult ListContactsByCompany()
        {
            return View();
        }
    }
}

EcoTrend Industry Project/Views/Home/ContactManagement.cshtml
@*@model IEnumerable<EcoTrend_Industry_Project.Contact>*@


@model PagedList.IPagedList<EcoTrend_Industry_Project.ViewModels.ContactVM>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Contact Management Area";
    if (User.Identity.IsAuthenticated)
    {
        Layout = "~/Views/Shared/_Layout.cshtml";
    }

}
<h2>Contact Management Area</h2>
@Html.ActionLink("Get All Emails", "GetContactEmails", "Home")
<br /><br />
@using (Html.BeginForm())
{
    <div class="col-md-6">
        @Html.TextBox("SearchString", null, new { @class = "form-control", placeholder = "Search by first name or last name" })
    </div>
    <div class="col-md-6">
        <input type="submit" value="Search" class="btn btn-default" />
    </div>
        <br /><br /><br />
}

<table class="table">
    <tr>
        <th class="hidden-sm hidden-xs">
            @*@Html.DisplayNameFor(model => model.contactID)*@
            Contact ID
        </th>
        <th>
            @*@Html.ActionLink("Company", "ContactManagement", new { sortOrder = ViewBag.DateSortParm })*@
            @* @Html.DisplayNameFor(model => model.Store.shortName)*@
            Store Name
        </th>
        <th class="hidden-sm hidden-xs">
            @*@Html.DisplayNameFor(model => model.branch)*@
            Department
        </th>
        <th>
            @Html.ActionLink("First Name", "ContactManagement", new { sortOrder = ViewBag.NameSortParm })
        </th>

        <th>
            @Html.ActionLink("Last Name", "ContactManagement", new { sortOrder = ViewBag.NameSortParm })

        </th>

        <th>
            @*@Html.DisplayNameFor(model => model.email)*@
            Email
        </th>
        <th>
            @* @Html.DisplayNameFor(model => model.telephone)*@
            Telephone
        </th>
        <th></th>
        <th></th>
        <th></th>
    </tr>
    @foreach (var thing in Model)
    {
        <tr>
            <td class="hidden-sm hidden-xs">
                @Html.DisplayFor(modelItem => thing.ContactID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => thing.StoreName)
            </td>
            <td class="hidden-sm hidden-xs">
                @Html.DisplayFor(modelItem => thing.Department)
            </td>
            <td>
                @Html.DisplayFor(modelItem => thing.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => thing.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => thing.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => thing.Telephone)
            </td>

            <td>
                <a href="@Url.Action("EditContact", "SalesRep", new { id = thing.ContactID})" title="Edit Contact">
                    <span class="glyphicon glyphicon-pencil"></span>
                </a>
                <span>|</span>
                <a href="@Url.Action("ContactNotes", "SalesRep", new { id = User.Identity.Name, contactId = thing.ContactID, firstName = thing.FirstName, lastName = thing.LastName} )">
                    <span class="glyphicon glyphicon-list-alt" title="View Notes">
                    </span>
                </a>
                <span>|</span>
                <a href="@Url.Action("AddNote", "SalesRep", new { contactId = thing.ContactID, firstName = thing.FirstName, lastName = thing.LastName })">
                    <span class="glyphicon glyphicon-plus" title="Add Note"></span>
                </a>
            </td>
        </tr>
    }
</table>

@{
    if (User.IsInRole("admin"))
    {
        <form method="get" action="/Home/CreateContact">
            <input id="Submit1" type="submit" value="Add Contact" class="btn btn-default pull-right" />
        </form>
    }
    else if (User.IsInRole("salesrep"))
    {
        @Html.ActionLink("Add Contact", "AddContact", "SalesRep", null, new { @class = "btn btn-primary" })
    }
}


Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("ContactManagement",
new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))

EcoTrend Industry Project/Views/Home/ContactMangAreaAndrew.cshtml
@model IEnumerable<EcoTrend_Industry_Project.ViewModels.ContactVM>

@{
    ViewBag.Title = "Contact Management Area";
    if (User.Identity.IsAuthenticated)
    {
        if (User.IsInRole("admin"))
        {
            Layout = "~/Views/Shared/_AdminLayout.cshtml";
        }
        else
        {
            Layout = "~/Views/Shared/_Layout.cshtml";
        }
    }

}

<div class="row">
    <div class="col-md-12">
        <h2>Contact Management Area</h2>
    </div>
</div>

<div class="row">
    <div class="hidden-xs hidden-sm col-md-12 col-lg-12">
        <div style="display: inline-block">
            <input class="input input-sm" placeholder="Comapny or Sales Rep. Name" />
            <button class="btn btn-primary">Search</button>
            <br /><br />
        </div>

        <table class="table">
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ContactID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FirstName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LastName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Telephone)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Branch)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Department)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.StoreID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.StoreName)
                </th>
                <th></th>
                <th></th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ContactID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FirstName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LastName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Email)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Telephone)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Branch)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Department)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.StoreID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.StoreName)
                    </td>
                    <td><a href="../SalesRep/EditContact"><span class="glyphicon glyphicon-pencil" title="Edit Contact"></span></a></td>
                    <td><a href="../SalesRep/ContactNotes"><span class="glyphicon glyphicon-list-alt" title="View Notes"></span></a></td>
                    <td>
                        <a href="@Url.Action("AddNote", "SalesRep", new { contactID = item.ContactID })">
                            <span class="glyphicon glyphicon-plus" title="Add Note"></span>
                        </a>
                    </td>
                </tr>
            }

        </table>
    </div>
</div>

EcoTrend Industry Project/Views/Home/CreateContact.cshtml
@model EcoTrend_Industry_Project.ViewModels.ContactVM

@if (User.Identity.IsAuthenticated)
{
    if (User.IsInRole("admin"))
    {
        Layout = "~/Views/Shared/_AdminLayout.cshtml";
    }
    else
    {
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
}


<h2>Add A Contact</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
     
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ContactID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.ContactID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telephone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Telephone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telephone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Branch, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Branch, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Branch, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Department, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Department, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Department, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StoreID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.StoreID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StoreID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.SalesRepID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.SalesRepID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SalesRepID, "", new { @class = "text-danger" })
            </div>
        </div>


        <br />
        <label for="email_subscription">Subscribed to Emails?</label>
        <input style="margin-bottom: 20px; margin-top: 10px;" type="checkbox" id="email_subscription" name="email_subscription" checked="checked" />
        <br />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-6">
                <input type="submit" value="Add Contact" class="btn btn-primary btn-block" />
            </div>
        </div>
    </div>
}

EcoTrend Industry Project/Views/Home/Delete.cshtml
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_LoginLayout.cshtml";
}

<h2>Delete</h2>

EcoTrend Industry Project/Views/Home/EditContact.cshtml
@model EcoTrend_Industry_Project.ViewModels.ContactVM

@{
    ViewBag.Title = "Edit Contact";
    if (User.IsInRole("admin"))
    {
        Layout = "~/Views/Shared/_AdminLayout.cshtml";
    }
    else
    {
        Layout = "~/Views/Shared/_Layout.cshtml";
    }
}

<h2>Edit Contact</h2>
<div><strong> Store Name</strong></div>
<select name="StoreID">
    @foreach (var item in Model.Stores)
            {
        <option value="@item.storeID">@item.name</option>

    }
</select>

<div><strong>Branch</strong></div>
<div>
    @Html.DisplayFor(model => model.Branch, new { htmlAttributes = new { @class = "form-control" } })
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />      
        <div class="form-group">
            @Html.LabelFor(model => model.Department, htmlAttributes: new { @class = "control-label col-md-2" })<br />
            <div class="col-md-6">
                @Html.EditorFor(model => model.Department, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Department, "", new { @class = "text-danger" })
            </div><br /><br />
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telephone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-6">
                @Html.EditorFor(model => model.Telephone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telephone, "", new { @class = "text-danger" })
            </div>
        </div>     
        <br />
        <br />
        <label for="email_subscription">Subscribed to Emails?</label>
        <input type="checkbox" checked="checked" />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-6">
                <input type="submit" value="Update Contact" class="btn btn-block btn-primary"/>
            </div>
        </div>
    </div>
}


<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

EcoTrend Industry Project/Views/Home/GetContactEmails.cshtml
@{
    ViewBag.Title = "GetContactEmails";
 
}

<h2>Contact Emails</h2>

<div class="container text-center">
    @foreach (var item in ViewBag.emailList)

    {
        @item
        <br/>
    }
</div>
   
   